/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public\models\g\g.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/g.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials['#F15A2BFF']} />
      <mesh geometry={nodes.Node2.geometry} material={materials['#F15A2BFF']} />
      <mesh geometry={nodes.Node3.geometry} material={materials['#F89820FF']} />
    </group>
  )
}

useGLTF.preload('/g.gltf')
